### ISSUE TITLE
Help with Error in running Sphinx to gh pages 

### ISSUE THREAD

**Issue by bcamino** [crystal-code-tools/CRYSTALpytools#79]
Hi @Spica-Vir ,

I hope you are well.

There is an error in running Sphinx to gh pages (https://github.com/bcamino/CRYSTALpytools/actions/runs/5401275406/jobs/9810852441).

I paste below the error log. It seems like it's an import in the thermodynamics file. I hope I didn't break the code when I did my last changes. Please let me know if that is the case and we can work on it together. Otherwise, it seems rather easy to fix, but I didn't want to change the file because you are much more familiar with it than I am.

Thanks,

Bruno

Configuration error:
  There is a programmable error in your configuration file:
  
  Traceback (most recent call last):
    File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/sphinx/config.py", line 354, in eval_config_file
      exec(code, namespace)  # NoQA: S102
    File "/home/runner/work/CRYSTALpytools/CRYSTALpytools/docs_source/conf.py", line 25, in <module>
      from CRYSTALpytools import __author__, __version__
    File "/home/runner/work/CRYSTALpytools/CRYSTALpytools/CRYSTALpytools/__init__.py", line 8, in <module>
      from CRYSTALpytools import thermodynamics
    File "/home/runner/work/CRYSTALpytools/CRYSTALpytools/CRYSTALpytools/thermodynamics.py", line 7, in <module>
      from CRYSTALpytools.crystal_io import Crystal_output
  ImportError: cannot import name 'Crystal_output' from 'CRYSTALpytools.crystal_io' (/home/runner/work/CRYSTALpytools/CRYSTALpytools/CRYSTALpytools/crystal_io.py)

**Comment by bcamino** [comment]
Closing this as we discussed it in the last PR
